# Generated by Django 5.1.2 on 2024-11-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(blank=True, max_length=100, null=True)),
                ('social_media_link', models.URLField(blank=True, null=True)),
                ('icon_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
